name: Auto Minify JS and CSS Files

on:
  push:
    branches: [ pull_requests#21 ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Auto Minify
      uses: nizarmah/auto-minify@minify-mjs-files

    - name: Auto committing minified files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Github Action: Auto Minified JS and CSS files"
        branch: ${{ github.ref }}
