name: Auto Minify JS and CSS Files

on:
  push:
    branches: [ pull_requests#17 ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Auto Minify with Admin Files Fix
      uses: alexmigf/auto-minify@fixes-file-names-ending-with-min

    - name: Auto committing minified files
      uses: stefanzweifel/git-auto-commit-action@v3.0.0
      with:
        commit_message: "Github Action: Auto Minified JS and CSS files"
        branch: ${{ github.ref }}
